[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--base-url http://www.uitestingplayground.com/ --browser chromium --video retain-on-failure --slowmo 500"
